image:
  file: .gitpod.Dockerfile
tasks:
  - name: Build & Run Tests
    init: mvn clean install
    command: mvn test -DLT_USERNAME=premkumarreddykarri668 -DLT_ACCESS_KEY=LT_hWR6qVDp4vQM0SWlKgoAAwTtZ2vY9F6ehPmsqw3m5C1GOxy
ports:
  - port: 8080
    onOpen: ignore
